test

diff --git a/.github/workflows/build_deb.yml b/.github/workflows/build_deb.yml
--- a/.github/workflows/build_deb.yml
+++ b/.github/workflows/build_deb.yml
@@ -74,8 +74,7 @@ jobs:
         working-directory: ./releases-ci/
         shell: bash
         run: |
-          echo "force_build=false" >> $GITHUB_OUTPUT
-          echo "---> Starting Install & Run Check"
+          STATUS=false
           docker compose up -d --wait
           i=0
           while [ $i -le 10 ]; do
@@ -84,25 +83,30 @@ jobs:
               echo "---> Docker Container is running. Try connecting to WebUI Port 8090 ..."
               until [ "$(curl --silent --show-error --connect-timeout 1 -I http://localhost:8090 | grep 'Hyperion')" ];
               do
-                echo "---> Hyperion is still starting up. try again in 3 seconds ..."
-                docker compose logs hyperion
-                sleep 3
+                echo "---> Hyperion is still starting up. try again in 5 seconds ..."
+                sleep 5
               done
               echo "---> Hyperion is up and running."
-              echo "force_build=true" >> $GITHUB_OUTPUT
+              STATUS=true
             else
-              echo "---> Docker Container could not be found yet, try again in 10 seconds ..."
-              sleep 10
+              echo "---> Docker Container could not be found yet, try again in 5 seconds ..."
+              sleep 5
             fi
           done
+          echo "---> Docker compose log:"
+          docker compose logs hyperion
           docker compose down
+          if [ "$STATUS" = false ] ; then
+            echo "---> Hyperion could not be started."
+            exit 1
+          fi
         env:
           distribution: ${{ matrix.os.distribution }}
           codename: ${{ matrix.os.codename }}
           platform: ${{ matrix.architecture[1] }}
 
       - name: ⬇ Checkout hyperion.ng
-        if: ${{ !inputs.install_run_check || steps.install_run_check.outputs.force_build  == 'true' }}
+        if: ${{ !inputs.install_run_check }}
         uses: actions/checkout@v4
         with:
           repository: ${{ inputs.repo_checkout }}
@@ -110,7 +114,7 @@ jobs:
           submodules: recursive
 
       - name: 🔧 Prepare
-        if: ${{ !inputs.install_run_check || steps.install_run_check.outputs.force_build  == 'true' }}
+        if: ${{ !inputs.install_run_check }}
         run: |
           echo '::group::Checking the version number'
             if [[ "${{ inputs.nightly }}" = true ]]; then
@@ -125,7 +129,7 @@ jobs:
           echo '::endgroup::'
 
       - name: 👷 Build
-        if: ${{ !inputs.install_run_check || steps.install_run_check.outputs.force_build  == 'true' }}
+        if: ${{ !inputs.install_run_check }}
         uses: ./releases-ci/.github/actions/build
         with:
           distribution: ${{ matrix.os.distribution }}
@@ -135,7 +139,7 @@ jobs:
           dockerArchitecture: ${{ matrix.architecture[1] }}
 
       - name: 📦 Upload
-        if: ${{ inputs.upload }} && ${{ !inputs.install_run_check || steps.install_run_check.outputs.force_build  == 'true' }}
+        if: ${{ inputs.upload && !inputs.install_run_check }}
         uses: actions/upload-artifact@v4
         with:
           name: ${{ format('artifact-{0}_{1}_{2}{3}', matrix.os.distribution, matrix.os.codename, matrix.architecture[0], matrix.os.qt_version  == '6' && '_qt6' || '')}}
